_target_: src.models.gfire_seg_models.UnetCNN_fire_model

dynamic_features: ${sel_dynamic_features}
static_features: ${sel_static_features}
hidden_size: 16
lstm_layers: 1
positive_weight: 0.9
lr: 0.01
lr_scheduler_step: 100
lr_scheduler_gamma: 0.1
weight_decay: 0.035
attention: false