_target_: src.models.greece_fire_models.CNN_fire_model

dynamic_features: ${sel_dynamic_features}
static_features: ${sel_static_features}
positive_weight: 0.5
lr: 0.01
lr_scheduler_step: 100
lr_scheduler_gamma: 0.1
weight_decay: 0.035
hidden_size: 64
