_target_: src.datamodules.greecefire_datamodule.GreeceFireDataModule

mode: conv
batch_size: 256
num_workers: 0
pin_memory: False
sel_dynamic_features: ${sel_dynamic_features}
sel_static_features: ${sel_static_features}
